### ISSUE TITLE
Add HTTPing

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/cnping#33]
Need to integrate httping into this, to allow for pinging in environments where icmp is disabled.

**Comment by dreua** [comment]
I see there are some changes related to HTTPing, but is it done yet? If I try it I only get errors:
```
$ cnping http://google.com
google.com: ERROR connecting
google.com: ERROR connecting
```

If the pinging via Http proves to be reliable and works without special permissions this would also be very promising for the Android version...

**Comment by dreua** [comment]
This fork works better for me: https://github.com/jvandenbroek/cnping
(Still a bit rough, e.g. it seems that the ping pauses while waiting for an answer.)

**Comment by cnlohr** [comment]
WHOOPS Try it now.

**Comment by dreua** [comment]
Yeah, now it works, thanks!

At the moment it's not possible to specify a port number or a specific URL - should we add this as a feature in the future or are these left out intentionally (maybe to make it harder to generate too much load on the server)?

And for some sites, e.g. http://vw.de (It's just a short URL, I am not affiliated with them ;)) and the "SimpleHTTPServer" from Python (`sudo python -m SimpleHTTPServer 80` maybe after pip installing the package; works without sudo for ports > 1024) the response goes missing on every second ping. I just fired up Wireshark and it seems like the server is closing the connection (might be because of "bad request 400" and/or a missing feature in SimpleHTTPServer) but Httping doesn't notice and just sends the next packet on the same (closed) TCP stream until it times out and starts a new connection.

I am just dumping my findings here in the hope it will help the future-me or someone else to make cnping even better, hoping this is okay. (I will fix them myself some day but don't know when this will happen and I won't complain if some else does it in the meantime.)

**Comment by cnlohr** [comment]
Issue resolved.

Both things are now available.

http://google.com:80/asdf

Does what you'd expect.
